#!/usr/bin/env bash

set -e
cd /autograder/source
mkdir -p /autograder/results

# Prepare submission
cp -r /autograder/submission/project /autograder/source/project

# Prepare test files
head -c 50000 < /dev/urandom > small_1.bin
head -c 48000 < /dev/urandom > small_2.bin
head -c 1000000 < /dev/urandom > large.bin

set +e
PROD=True python3 grader.py